### PR TITLE
[TIMOB-19057] Add Windows support

### PR DESCRIPTION
**Pull request by infosia**
[[TIMOB-19057](https://jira.appcelerator.org/browse/TIMOB-19057)]

This is to make the sample work on Windows. Should work once https://github.com/appcelerator/titanium_mobile_windows/pull/370 is merged.

### CODE REVIEW

**Comment by garymathews** [comment]
@infosia I can only mark one item as done. When selecting other items I don't get a prompt. Also the text box when adding an item is scaled so it is off screen.

**Comment by infosia** [comment]
@garymathews Fix for prompt issue: [TIMOB-19219](https://jira.appcelerator.org/browse/TIMOB-19219). 

The width issue for the components are because of `width: '300dp'`. Actual pixel calculation are done around [UI/src/WindowsViewLayoutDelegate.cpp#L841](https://github.com/appcelerator/titanium_mobile_windows/blob/master/Source/UI/src/WindowsViewLayoutDelegate.cpp#L841), looks like 300dp is too big.  Do you think we need to do like this? 

``` javascript
width: isWindowsPhone ? '200dp' : '300dp`,
```

**Comment by garymathews** [comment]
Yes, that's what I've done in `Geocoder`. Although I still don't think the scaling is correct. Why should we need to use a different `dp` on Windows Phone? I think I'll take another look at scaling.

**Comment by garymathews** [comment]
I've tested it using the latest `titanium_mobile_windows` build. After adding the first item the buttons in any additional prompts don't work.

**Comment by infosia** [comment]
Pushed a fix for it: https://github.com/appcelerator/titanium_mobile_windows/pull/378

**Comment by garymathews** [comment]
CR: PASS
FR: PASS

**Pull request merged**
